# Generated by Django 4.1.3 on 2023-07-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0003_alter_order_date_placed_alter_product_seller_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='details',
        ),
    ]
